name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform:
        - os: ubuntu-latest
        - os: macos-latest
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.1.0

      - name: install deps (Ubuntu)
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          # TODO: figure out why kcov doesn't work
          sudo apt-get install kcov
          sudo apt-get install tree

      - name: install deps (macOS)
        if: matrix.platform.os == 'macos-latest'
        run: |
          # TODO: figure out why kcov doesn't work
          brew install kcov
          brew install tree

      - name: Run Tests
        # TODO: figure out why kcov doesn't work
        # run: npm run cov:noopen
        run: |
          rm -rf ~/.nave
          bash --version
          COV=1 bash test/run.sh
          # bash test/cases/installed.sh #npm run test
          # bash test/cases/nave-fetch.sh #npm run test
          # cat snapshots/nave-fetch

      # TODO: figure out why kcov doesn't work
      # - name: Copy Coverage to Docs Folder
      #   run: |
      #     rm -rf public-coverage-report
      #     mv coverage public-coverage-report
      #
      # - name: Deploy Coverage Report
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{secrets.GITHUB_TOKEN}}
      #     publish_dir: ./public-coverage-report
      #     user_name: 'nave-coverage-bot'
      #     user_email: 'nave-coverage-bot@example.com'
