name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform:
        - os: ubuntu-latest
        - os: macos-latest
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1.1.0

      - name: install deps
        run: |
          brew install tree
          brew install kcov

      - name: Run Tests
        run: COV=1 bash test/run.sh
